import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.wokine}>
          <Image src="/wokine.svg" width={100} height={15} alt="Wokine" draggable="false" />
        </div>

        <div className={styles.thumb}>
          <Image src="/thumb-up-dynamic-color.png" width={600} height={600} alt="Pouce levéééé" draggable="false" />
        </div>
      </main>
    </div>
  )
}
